[2024-11-05T13:59:00.016+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T13:59:00.041+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: producer.update_dataset scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:59:00.050+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: producer.update_dataset scheduled__2024-11-04T00:00:00+00:00 [queued]>
[2024-11-05T13:59:00.050+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-05T13:59:00.065+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): update_dataset> on 2024-11-04 00:00:00+00:00
[2024-11-05T13:59:00.074+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3795) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T13:59:00.076+0000] {standard_task_runner.py:72} INFO - Started process 3799 to run task
[2024-11-05T13:59:00.078+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'producer', 'update_dataset', 'scheduled__2024-11-04T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/producer.py', '--cfg-path', '/tmp/tmp7e2dhdif']
[2024-11-05T13:59:00.080+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask update_dataset
[2024-11-05T13:59:00.163+0000] {task_command.py:467} INFO - Running <TaskInstance: producer.update_dataset scheduled__2024-11-04T00:00:00+00:00 [running]> on host 3a4fba066ec8
[2024-11-05T13:59:00.278+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='producer' AIRFLOW_CTX_TASK_ID='update_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-04T00:00:00+00:00'
[2024-11-05T13:59:00.287+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-05T13:59:00.287+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-05T13:59:00.288+0000] {logging_mixin.py:190} INFO - Current task name:update_dataset state:running start_date:2024-11-05 13:59:00.042260+00:00
[2024-11-05T13:59:00.288+0000] {logging_mixin.py:190} INFO - Dag name:producer and current dag run status:running
[2024-11-05T13:59:00.289+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T13:59:00.291+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/producer.py", line 19, in update_dataset
    with open(my_dataset.uri,'a+') as f:
              ^^^^^^^^^^
NameError: name 'my_dataset' is not defined
[2024-11-05T13:59:00.317+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-05T13:59:00.318+0000] {logging_mixin.py:190} INFO - Task start:2024-11-05 13:59:00.042260+00:00 end:2024-11-05 13:59:00.312645+00:00 duration:0.270385
[2024-11-05T13:59:00.321+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): update_dataset> dag:<DAG: producer> dagrun:<DagRun producer @ 2024-11-04 00:00:00+00:00: scheduled__2024-11-04T00:00:00+00:00, state:running, queued_at: 2024-11-05 13:58:53.365766+00:00. externally triggered: False>
[2024-11-05T13:59:00.321+0000] {logging_mixin.py:190} INFO - Failure caused by name 'my_dataset' is not defined
[2024-11-05T13:59:00.322+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=producer, task_id=update_dataset, run_id=scheduled__2024-11-04T00:00:00+00:00, execution_date=20241104T000000, start_date=20241105T135900, end_date=20241105T135900
[2024-11-05T13:59:00.357+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T13:59:00.358+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task update_dataset (name 'my_dataset' is not defined; 3799)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/producer.py", line 19, in update_dataset
    with open(my_dataset.uri,'a+') as f:
              ^^^^^^^^^^
NameError: name 'my_dataset' is not defined
[2024-11-05T13:59:00.417+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T13:59:00.435+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T13:59:00.437+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
