[2024-11-05T09:04:51.537+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T09:04:51.555+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.process_user manual__2024-11-05T09:04:39.842816+00:00 [queued]>
[2024-11-05T09:04:51.563+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.process_user manual__2024-11-05T09:04:39.842816+00:00 [queued]>
[2024-11-05T09:04:51.564+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-05T09:04:51.580+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): process_user> on 2024-11-05 09:04:39.842816+00:00
[2024-11-05T09:04:51.590+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T09:04:51.591+0000] {standard_task_runner.py:72} INFO - Started process 177 to run task
[2024-11-05T09:04:51.592+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'manual__2024-11-05T09:04:39.842816+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmpmfxssl0m']
[2024-11-05T09:04:51.593+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask process_user
[2024-11-05T09:04:51.647+0000] {task_command.py:467} INFO - Running <TaskInstance: user_processing.process_user manual__2024-11-05T09:04:39.842816+00:00 [running]> on host 3a4fba066ec8
[2024-11-05T09:04:51.732+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T09:04:39.842816+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T09:04:39.842816+00:00'
[2024-11-05T09:04:51.734+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-05T09:04:51.735+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-05T09:04:51.736+0000] {logging_mixin.py:190} INFO - Current task name:process_user state:running start_date:2024-11-05 09:04:51.555633+00:00
[2024-11-05T09:04:51.736+0000] {logging_mixin.py:190} INFO - Dag name:user_processing and current dag run status:running
[2024-11-05T09:04:51.736+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T09:04:51.737+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/user-processing.py", line 15, in _process_user
    user = ti.xcom_pull(task_id = 'extract_user')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-11-05T09:04:51.751+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-05T09:04:51.752+0000] {logging_mixin.py:190} INFO - Task start:2024-11-05 09:04:51.555633+00:00 end:2024-11-05 09:04:51.751103+00:00 duration:0.19547
[2024-11-05T09:04:51.753+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_user> dag:<DAG: user_processing> dagrun:<DagRun user_processing @ 2024-11-05 09:04:39.842816+00:00: manual__2024-11-05T09:04:39.842816+00:00, state:running, queued_at: 2024-11-05 09:04:39.880899+00:00. externally triggered: True>
[2024-11-05T09:04:51.753+0000] {logging_mixin.py:190} INFO - Failure caused by TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-11-05T09:04:51.754+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=user_processing, task_id=process_user, run_id=manual__2024-11-05T09:04:39.842816+00:00, execution_date=20241105T090439, start_date=20241105T090451, end_date=20241105T090451
[2024-11-05T09:04:51.768+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T09:04:51.769+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task process_user (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 177)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/user-processing.py", line 15, in _process_user
    user = ti.xcom_pull(task_id = 'extract_user')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-11-05T09:04:51.807+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-05T09:04:51.828+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T09:04:51.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
